name: flat
on:
  schedule:
    - cron: "0 0 * * *" # faily
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      #- name: Fetch pdfs
      #  uses: githubocto/flat@v3
      #  with:
      #    http_url: https://na.taqa.com/wp-content/uploads/sites/11/2021/07/TAQA-North-Ltd.-2019-ESTMA-Refile-Report_July-2021.pdf
      #    downloaded_filename: pdfs/TAQA-North-Ltd.-2019-ESTMA-Refile-Report_July-2021.pdf
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://github.com/blairdrummond/test-flatdata/raw/main/excel/SAMPLE-ESTMA-data.xlsx
          downloaded_filename: SAMPLE-ESTMA-data.xlsx # The http_url gets saved and renamed in our repository as this file
          postprocess: ./postprocess.ts # A postprocessing javascript or typescript file written in Deno
      - name: Fetch payments
        uses: githubocto/flat@v3
        with:
          http_url: https://github.com/blairdrummond/test-flatdata/raw/main/excel/System_All_Payments_DataDump.xlsx
          downloaded_filename: System_All_Payments_DataDump.xlsx # The http_url gets saved and renamed in our repository as this file
          postprocess: ./postprocess.ts # A postprocessing javascript or typescript file written in Deno
